### ISSUE TITLE
Asterisk-12-CEL-Specification links in docs.asterisk.org doesn't exist, but referenced

### ISSUE THREAD

**Issue by Stevehans** [asterisk/documentation#10]
Various references to https://docs.asterisk.org/Asterisk-12-CEL-Specification
Old copy at https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+CEL+Specification still exists

**Comment by jcolp** [comment]
The page is now on the new docs site here: https://docs.asterisk.org/Configuration/Reporting/Channel-Event-Logging-CEL/CEL-Specification/
