### ISSUE TITLE
!!! tip not tipping

### ISSUE THREAD

**Issue by chrsmj** [asterisk/documentation#116]
Occasionally there are some Tips like:

`!!! tip `

...that maybe were a callout or tooltip or box with a border ?

See 3rd paragraph at: https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/What-to-Download/#asterisk

And a bit below that in the bottom of the DAHDI section: https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/What-to-Download/#dahdi

**Comment by seanbright** [comment]
Dupe of #79

**Comment by gtjoseph** [comment]
Yeah I have a sticky note to convert all of the `!!!` admonitions to the new `///` style because the new style uses a closing `///` which makes it easier to put other things like code inside the admonition.

**Comment by seanbright** [comment]
Can you link that documentation?

**Comment by gtjoseph** [comment]
https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/admonition/

I'm going to update the README right now.

**Comment by gtjoseph** [comment]
I also have adding a style guide on my list but I never seem to find the time.

**Comment by gtjoseph** [comment]
[README.md](https://github.com/asterisk/documentation/blob/main/README.md) updated.
