### ISSUE TITLE
context mistake in documentation Configure Asterisk's built-in HTTP server for WebRTC

### ISSUE THREAD

**Issue by pyropecs** [asterisk/documentation#121]
<code>text[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/etc/asterisk/keys/asterisk.crt
tlsprivatekey=/etc/asterisk/keys/asterisk.key
</code>

in line 1 the it should be [general] context not text[general].
documentation path : Configuration -> WebRTC -> Configuring Asterisk for WebRTC Clients -> Configure Asterisk's built-in HTTP server

**Comment by gtjoseph** [comment]
Thanks for the report.  I've fixed this one plus a whole bunch of other issues of the same type.  The fixes should be live in 15 minutes or so.
