### ISSUE TITLE
Values in tables are off

### ISSUE THREAD

**Issue by ffloimair** [asterisk/documentation#17]
E.g. in the table [https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/Module_Configuration/res_pjsip/?h=res_pjsip#endpoint]

The “Type” value is shown in the “Default Value” column, the “Default Value” value is in the “Description” column. Looks like when processing the data it seems to skip every second column.

<img width="1117" alt="image" src="https://github.com/asterisk/documentation/assets/6363261/d33ed64a-c8a2-4776-9137-f8b6be7f2358">

**Comment by gtjoseph** [comment]
Should be fixed now.
