### ISSUE TITLE
Options formatting is messed up

### ISSUE THREAD

**Issue by InterLinked1** [asterisk/documentation#20]
Possibly a wider issue, but here's an example of a page that is completely malformatted (scroll down to "Syntax"): https://docs.asterisk.org/Asterisk_20_Documentation/API_Documentation/Dialplan_Applications/Dial/

**Comment by ffloimair** [comment]
Stumbled upon the same. I guess you mean that e.g. options are all in one big block, which makes it hard to find what you are looking for. They should be on a new line each.

**Comment by gtjoseph** [comment]
Yeah, I think the stylesheet that converts the XML to markdown has an issue.  I'm looking at it.

**Comment by gtjoseph** [comment]
Should be fixed now.

**Comment by InterLinked1** [comment]
Much better now, but still some lingering "combining" on some pages, e.g.:

https://docs.asterisk.org/Development/Policies-and-Procedures/Historical-Policies-and-Procedures/Patch-Contribution-Process/

```
!!! note Read More! This page links to many other pages on the wiki that provide deeper explanations regarding reporting of issues, writing of patches, and participation in the Asterisk project. Please read the information on those linked pages! Having well tested, high quality patches proposed to the Asterisk project helps everyone.

On This PageAdditional InformationSubmitting a Patch
````
