### ISSUE TITLE
Asterisk REST Interface links with multiple word methods are broken

### ISSUE THREAD

**Issue by daninmadison** [asterisk/documentation#21]
If you go to docs.asterisk.org and the Asterisk REST Interface (at least in both 18 and 20 versions).  Go to the Channels.
[https://docs.asterisk.org/Asterisk_20_Documentation/API_Documentation/Asterisk_REST_Interface/Channels_REST_API/](url)

There is a list of Method and path links.
Most work, but a few do not. Not sure if the problem is the link should use all lower case or if the section should be a blend up upper/lower case.

Originate with ID attempts to jump to originateWithId (should be originatewithid)
Continue Dialplan attempts to jump to continueInDialplan (the link that works is continueindialplan)
Play with playback id attempts to jump to playWithId (should be playwithid)
The snoop attempts to jump to the snoopChannel (should be snoopchannel)
Snoop with channel id attempts to jump to snoopChannelWithId (should be snoopchannelwithid)
ExternalMedia attempts to go to externalMedia (link that works is externalmedia)

![image](https://github.com/asterisk/documentation/assets/58079560/3bcbd314-2a6e-4f68-b7b0-03dda52e6dcb)

**Comment by gtjoseph** [comment]
These should all be fixed now.
