### ISSUE TITLE
"Basic PBX Functionality" section of docs seems unordered, missing pages? 

### ISSUE THREAD

**Issue by larcher** [asterisk/documentation#24]
I'm brand new to Asterisk and looking for a good place to get started.  A web search landed me on the page titled [The Most Basic PBX](https://docs.asterisk.org/Deployment/Basic-PBX-Functionality/The-Most-Basic-PBX/)  .. which sounds perfect, a basic PBX to "help [me] learn the fundamentals of configuring Asterisk" is exactly what I'm after.  But that page only covers "Requirements and Assumptions" and it's not clear where to go next from there.  

Going up a level in the docs takes me to [Basic PBX Functionality](https://docs.asterisk.org/Deployment/Basic-PBX-Functionality/) which is another introductory page. The pages under that page seem like the right instructions, but they seem out of order (or in alphabetical order by title?).    For example, "Adding Voice Mail" is the first subpage listed, but that's a short page, and sounds like something I'd do after setting up other more basic things. "Creating Dialplan Extensions" is next, but it starts with "The **last** things we need to do ..." so I assume that's not the right place to start either.  

Aha! I just found the [Hello World page](https://docs.asterisk.org/Getting-Started/Hello-World/#make-the-call) .. maybe this is a better place to start?   Would be great to link to that page from more places, and make it clear that's the recommended place to start for complete newbies (assuming that's true).

Anyway, I expect I'll be able to eventually figure things out, but just wanted to share my experience as a new user trying to figure out how to get started with Asterisk.

**Comment by gtjoseph** [comment]
It's not perfect but it should be better now.  Take a look.
