### ISSUE TITLE
Side menu is clunky

### ISSUE THREAD

**Issue by chrsmj** [asterisk/documentation#27]
After clicking through documentation using the left-side menu, the page reloads with correct information on the right-side, but it seems  that the left-side menu stays stuck at the top and does not scroll down automatically to the selected menu item in some small percent of cases, such as when clicking on the 91st item in the sub-menu.

Steps to reproduce (on Firefox 102.13.0 ESR from July 2023):

1. Click on Originate AMI Action in Asterisk Version 20 documentation: https://docs.asterisk.org/Asterisk_20_Documentation/API_Documentation/AMI_Actions/Originate/
2. Click on PJSIPNotify in the left-side menu. No problem, it works, page loads and menu scrolls. Note this is the 90th menu item.
3. Click on PJSIPQualify in the left-side menu. Look, it loads the page, but the menu does not scroll. This is the 91st menu item in the AMI Action section.
4. Repeat click on PJSIPRegister, the 92nd item, and it is the same problem as PJSIPQualify.
5. The problem continues for many of the items after that, but it does work correctly for a few eg. Park, QueueAdd, etc. Seemingly at random which items work and which don't, but it is consistent on the items. Which makes you go grrr.

**Comment by gtjoseph** [comment]
Yeah I see that with many of those nav bar entries.  That's really weird.  We don't generate that nav bar ourselves so it may take a bit of digging to figure out what's going on.

**Comment by chrsmj** [comment]
Works now, thanks!
