### ISSUE TITLE
"Installing Asterisk From Source" is out of order

### ISSUE THREAD

**Issue by linuxfingers** [asterisk/documentation#33]
The instruction set for "[Installing Asterisk From Source](https://docs.asterisk.org/Getting-Started/Installing-Asterisk/Installing-Asterisk-From-Source/)" list is ordered alphabetically, instead of chronologically. It is very difficult to follow along with the installation process directly from the documentation, and seems it is likely related to the same issue affecting #24.

**Comment by gtjoseph** [comment]
I've reorganized the section.  It's not perfect but it should be in order now.
