### ISSUE TITLE
Documentation of parameters/body for ARI

### ISSUE THREAD

**Issue by sboily** [asterisk/documentation#38]
Hello,

It's complicated to understand the body of a POST for the REST API. Here an example with externalMedia.

<img width="967" alt="Capture d’écran, le 2023-10-19 à 10 34 32" src="https://github.com/asterisk/documentation/assets/5470187/38b8fdf7-ef6c-48ef-bfa4-dc633a0a0c7b">

**Comment by gtjoseph** [comment]
Yeah, that doesn't look right.  The default and allowed values should be indented.  I'll see if I can fix the script that generated those docs.

**Comment by sboily** [comment]
Thank you, it's clearly better.
