### ISSUE TITLE
Asterisk REST Data Models - "Message" Subtype listing is wrong

### ISSUE THREAD

**Issue by whiplashscorpion** [asterisk/documentation#41]
https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/Asterisk_REST_Interface/Asterisk_REST_Data_Models/#message

Issue: The subtypes of the "Message" model should only be "MissingParams", "Event". The paragraph subtype section here contains all the Event subtypes.

![Screenshot 2024-01-18 at 12 47 06 pm](https://github.com/asterisk/documentation/assets/44941606/fcd12bf3-afce-4018-8d3e-7361f5c47a88)

**Comment by gtjoseph** [comment]
@whiplashscorpion The documentation generator specifically expands all the subtypes.  Can you tell my why that should not be the case?

**Comment by gtjoseph** [comment]
No response...closing.
