### ISSUE TITLE
Note parsing does not parse end note

### ISSUE THREAD

**Issue by InterLinked1** [asterisk/documentation#65]
https://docs.asterisk.org/Asterisk_21_Documentation/API_Documentation/Dialplan_Functions/CHANNEL/

The note starting at "If not specified, 'audio' is used by default." is never closed.

Looking at the underlying XML documentation in `channels/pjsip/dialplan_functions_doc.xml`, it appears to be correct (the note is properly closed):

```
<enumlist>
	<enum name="audio">
		<para>Retrieve information from the audio media stream.</para>
		<note><para>If not specified, <literal>audio</literal> is used
		by default.</para></note>
	</enum>
	<enum name="video">
		<para>Retrieve information from the video media stream.</para>
	</enum>
</enumlist>
```

**Comment by seanbright** [comment]
The full contents of the `!!! note` admonition (same will `!!! warning`) needs to have the same amount of leading indentation as the surrounding list items for this to render properly. Right now we put it all at the beginning of a line during the XSLT processing.

**Comment by gtjoseph** [comment]
I _think_ switching to the `/// admonition` style might fix this because it doesn't require the leading spaces in the first sentence and it has a closing `///` delimiter.  It looks like this...

```
/// info | Some Title
<any text>
///

I'll try it.

**Comment by gtjoseph** [comment]
Nope made things worse.  I think not using the admonitions at all may be better.  Just using `**Note: <note text>**` would look like this when used in an enum/param list...

![image](https://github.com/asterisk/documentation/assets/1205666/71578751-5ca3-4002-a701-ea5b3cbf5aad)


When used in normal text, it'd look like this...

![image](https://github.com/asterisk/documentation/assets/1205666/91eaca95-0453-4866-be38-06ff94605009)

What do you think?

**Comment by InterLinked1** [comment]
> Nope made things worse. I think not using the admonitions at all may be better. Just using `**Note: <note text>**` would look like this when used in an enum/param list...
> 
> ![image](https://private-user-images.githubusercontent.com/1205666/311866260-71578751-5ca3-4002-a701-ea5b3cbf5aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTI4MzAsIm5iZiI6MTcxMDE5MjUzMCwicGF0aCI6Ii8xMjA1NjY2LzMxMTg2NjI2MC03MTU3ODc1MS01Y2EzLTQwMDItYTcwMS1lYTViM2NiZjVhYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMjEyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDAxYTY4YmJhOGYwMDZmZjkyMjk5M2QzNzNiYjA0OGFmNWVlMzIzNjA2NTJjYzUyMTRkMjRkM2VhNzFlMmRjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OZ24pJs2nvciQmTR1TMTD6gzvi89U0lHC9GES_lGOsE)
> 
> When used in normal text, it'd look like this...
> 
> ![image](https://private-user-images.githubusercontent.com/1205666/311866083-91eaca95-0453-4866-be38-06ff94605009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxOTI4MzAsIm5iZiI6MTcxMDE5MjUzMCwicGF0aCI6Ii8xMjA1NjY2LzMxMTg2NjA4My05MWVhY2E5NS0wNDUzLTQ4NjYtYmUzOC0wNmZmOTQ2MDUwMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTFUMjEyODUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODZlZTk5YjFiMWU3YjRmMmMxYzljMGMxM2MwNWUwZjhhNWYyZjM3NWU1NzI2M2Y1MTQ5Njk5ZjViN2VkYmEwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nYQOTU6dNFKxOXFdPuV7WwBWdlaOL9Vc2892QuBvkhA)
> 
> What do you think?

I liked having a red block for warnings, like in the old docs, since they're mot distinguished than just boldface, but if there's not an easy way to retain that, I guess it is what it is.

**Comment by gtjoseph** [comment]
I'll take another pass at it tomorrow and see if I can keep the admonitions but still get them to render correctly in both lists and regular paragraphs.

**Comment by gtjoseph** [comment]
Sorry guys, I don't think there's a way to make admonitions work when they're inside enum lists without serious xslt work and imposing stricter rules on the XML itself.  I'll continue to research though.

**Comment by gtjoseph** [comment]
OK, I think I got it figured out.  Checkout the PR and build it if you want to test, otherwise I'll merge it on Wednesday.
