### ISSUE TITLE
Clarification in Stir/Shaken Outgoing Call Flow section

### ISSUE THREAD

**Issue by oza4h07** [asterisk/documentation#81]
In  Outgoing Call Flow section, point 7 from [1], you can read, that “If there’s no “tn” object matching the caller-id, skip attestation and continue the call.”
Can this matching be further clarified or detailed using an example, such as bellow ?

"Example:
For instance, if CALLERID(num) is valued to 123456789012 and “stir_shaken show tns” displays a line “TN: 123456789012” , then there is match.

Alternatively, if CALLERID(num) is valued to +123456789012 (+E164 notation) and “stir_shaken show tns” still displays a line “TN: 123456789012” , then there is NO match."

[1] [STIR-SHAKEN - Asterisk Documentation](https://docs.asterisk.org/Deployment/STIR-SHAKEN/)

**Comment by oza4h07** [comment]
IMHO, one interesting addition could describe what happens in case of contradicting information in P-Asserted-Identity and From headers, in case P-Asserted-Identity  is customized in dialplan.
Alternatively, a warning against customizing P-Asserted-Identity in dialplan may makes sense.

**Comment by gtjoseph** [comment]
Thanks for the comments.  I'll clarify the documentation.

**Comment by gtjoseph** [comment]
Done.
