### ISSUE TITLE
Broken toggle content in docs

### ISSUE THREAD

**Issue by Wryhder** [asterisk/documentation#86]
There seems to be broken toggle functionality for content that is meant to be hidden by default. For example, in _Fundamentals > Types of Asterisk Modules_.

![broken toggle content-fundamentals-types of asterisk modules](https://github.com/asterisk/documentation/assets/21000445/cb43caf0-4fb8-4120-90f0-a51d5a284399)

Possibly related to issue #79 .

**TODO:** Update issue with other pages, if any, with the same issue.

**Comment by Wryhder** [comment]
Possibly related to issue #79 .

**Comment by gtjoseph** [comment]
Yeah, that didn't convert from the old wiki very well.  I just pushed up a fix which should publish shortly.

**Comment by Wryhder** [comment]
> Yeah, that didn't convert from the old wiki very well. I just pushed up a fix which should publish shortly.

Great, thank you! Will you close this issue, or should I?
