### ISSUE TITLE
Asterisk 20 & 21 upgrade links broken

### ISSUE THREAD

**Issue by nexbridge** [asterisk/documentation#91]
In https://docs.asterisk.org/Asterisk_20_Documentation/Upgrading/ the link goes to https://raw.githubusercontent.com/asterisk/asterisk/20/UPGRADE.txt which is currently returning a 404, and similarly for https://docs.asterisk.org/Asterisk_21_Documentation/Upgrading/.

**Comment by gtjoseph** [comment]
Fixed.  Should publish in a few minutes.
